%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_rpc_compile
-ifndef(MSG_H).
-define(MSG_H, true).

%%%===================================================================
%%% cmd
%%%===================================================================
-ifndef(CMD_MSG_BASE).
-define(CMD_MSG_BASE, 0). %% msg_base
-define(CMD_MSG_BASE_KEY, 'msg_base'). %% 0
-endif.

-define(CMD_MSG_BASE_HEARTBEAT_REQ, 0). %% heartbeat_req
-define(CMD_MSG_BASE_HEARTBEAT_RESP, 1). %% heartbeat_resp

-endif.