%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.27.5

-ifndef(msg_base_pb).
-define(msg_base_pb, true).

-define(msg_base_pb_gpb_version, "3.27.5").

-ifndef('HEARTBEAT_REQ_PB_H').
-define('HEARTBEAT_REQ_PB_H', true).
-record(heartbeat_req,
        {id                             % = 1, uint64
        }).
-endif.

-ifndef('HEARTBEAT_RESP_PB_H').
-define('HEARTBEAT_RESP_PB_H', true).
-record(heartbeat_resp,
        {id                             % = 1, uint64
        }).
-endif.

-endif.
